name: Build & Deploy serverless

env: 
  ARTIFACT_NAME: csye6225-webapp-${{ github.sha }}.zip
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: fall2021-dg
  AWS_REGION: us-east-1
  
on:
  push:
    branches: [main]

jobs:
  ci_cd:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2
        
      - name: Build Deployment Artifact
        run: |
          mkdir codedeploy_artifact
          zip -r ${{ env.ARTIFACT_NAME }} index.js
          pwd
          ls -al
          mv ${{ env.ARTIFACT_NAME }} codedeploy_artifact/
          ls -al
          pwd
          cd codedeploy_artifact
          pwd
          ls -al
          cd ..
          pwd
          ls -al

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy Artifact to S3
        run: |
          aws s3 sync ./codedeploy_artifact s3://${{ secrets.S3_CODEDEPLOY_BUCKET }}


      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          echo $(ls)
          aws lambda update-function-code \
                --function-name  lambda_function_name \
                --zip-file fileb://./codedeploy_artifact/${{ env.ARTIFACT_NAME }} \
                --region us-east-1
